### ISSUE TITLE
函数章节下函数命名参数示例执行报错

### ISSUE THREAD

**Issue by ixiaofeng** [lydiandy/vlang_note#16]
fn main(){
	add(User{name:'jack',age:22}) //标准方式
	add({name:'tom',age:23}) //简短方式,省略类型
	add(name:'tt',age:33) //更简短的方式,省略类型和大括号,有命名参数调用的感觉
}

error: cannot initialize a struct with a map

结构体章节下有同样的内容

**Comment by lydiandy** [comment]
@ixiaofeng ，谢谢，已改，新的map语法改了，所以原来的第二种结构体简短模式估计就不支持了。
